"""Constants for the BlueSight integration."""
from __future__ import annotations

DOMAIN = "bluesight"
DEFAULT_STORM_WINDOW_S = 300.0
DEFAULT_STORM_THRESHOLD = 5
DEFAULT_POLL_INTERVAL_S = 30
DEFAULT_STALLED_THRESHOLD_S = 180.0
DEFAULT_REBOOT_WINDOW_S = 600.0
DEFAULT_REBOOT_THRESHOLD = 3
